.github/stale.yml
This PR adds the stale bot to automatically close an issue after 7 days (still to be agreed by the team) of inactivity.
=> chore(automation): add stale.yml with config

.changeset/ten-laws-notice.md, packages/sdk-client/src/client-builder/ClientBuilder.ts, packages/sdk-client/src/http-user-agent/create-user-agent.ts, packages/sdk-client/src/sdk-middleware-auth/base-auth-flow.ts, packages/sdk-client/src/sdk-middleware-auth/build-requests.ts, packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/test/client-builder.test/client-builder.test.ts, packages/sdk-client/test/http.test/http.test.ts
Fix the issues with node environments on different platforms by
=> Fix issues with Buffer and node process

packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/src/types/sdk.d.ts, packages/sdk-client/test/http.test/http.test.ts
- add retryCodes option to HttpMiddlewareOptions
- add check to ensure retryCodes is not null or undefined
- extend feature to include status message code also
- add unit test
This adds options to allow customers retry requests on a given status (error) codes.
- Tests
https://github.com/commercetools/commercetools-sdk-typescript/issues/225
=> Add Status and Message (Error) Code Retry Options

.changeset/small-numbers-peel.md, packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/src/types/sdk.d.ts, packages/sdk-client/test/http.test/http.test.ts
Add options to include or exclude original client request from error response
[#240](https://github.com/commercetools/commercetools-sdk-typescript/issues/240)
=> Add includeRequestInErrorResponse to HttpMiddlewareOptions

package.json, yarn.lock
- Husky version 8.x requires `node.js` version >=14
=> Revert husky to version 7.0.4

packages/importapi-sdk/test/misc.test.ts, webpack.config.js
=> Chore: Replace importSinks method with importContainers

examples/me/README.md
=> Fix incorrect list of env variables in me endpoint README.md file

.github/workflows/release.yml
=> Add slack notification on SDK publish

.changeset/empty-otters-bow.md, examples/me/README.md, examples/me/server/src/utils/options.ts, packages/sdk-client/src/client-builder/ClientBuilder.ts, packages/sdk-client/src/sdk-middleware-http/http.ts
=> Fix content-type to allow application/graphql

.changeset/violet-timers-sin.md, packages/sdk-client/src/client-builder/ClientBuilder.ts
Changes the `withExistingTokenFlow` type so that the second argument, `options` is optional.
Currently as the second argument is required but you don't need to alter the options you need to pass an empty object to appease TypeScript:
`.withExistingTokenFlow('random-token', {})` 
[Mentioned in issue 319](https://github.com/commercetools/commercetools-sdk-typescript/issues/319)
By making the second argument optional:
```typescript
withExistingTokenFlow(
authorization: string,
options?: ExistingTokenMiddlewareOptions
)
```
=> fix: made options to withExistingTokenFlow optional

packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/test/http.test/http.test.ts
=> Fix requests with image/* header content-type

.changeset/moody-hornets-work.md, packages/sdk-client/src/sdk-middleware-http/http.ts
=> Fix issue with buffer request body 

.changeset/lucky-tomatoes-join.md, packages/history-sdk/package.json, packages/importapi-sdk/package.json, packages/ml-sdk/package.json, packages/platform-sdk/package.json, packages/sdk-client/package.json
Nodejs version 12 is already in `end-of-life` hence a need to upgrade this repository to use node version greater than or equal to 14
#340
=> Upgrade node to version 14

examples/me/client/package.json, examples/me/client/yarn.lock, examples/react/package.json, examples/react/yarn.lock
Probably we will upgrade `html-loader` to the next version since it is not including at least the version 5.14.2 of the library `terser` which is a vulnerability
https://github.com/commercetools/commercetools-sdk-typescript/security/dependabot/76
Another place where there is the vulnerability is the library `@manypkg/cli` which has still the dependency on this library which is not maintained anymore https://github.com/changesets/changesets/blob/main/packages/get-workspaces/src/index.ts and it has an old version of the library `package-json` which has a dependency of a vulnerable version of the `got` library 
https://github.com/commercetools/commercetools-sdk-typescript/security/dependabot/68
I opened a PR in both the libraries, let's see
=> chore(package): upgraded some library in the me example folder

.changeset/happy-carpets-deliver.md, packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/src/types/sdk.d.ts, packages/sdk-client/test/http.test/http.test.ts
The current behavior of the client is to retry on a timeout, but immediately abort again due to the re-use of the AbortController. This change does one adjustment and introduces a new option
By default, aborted requests will not be retried.
This is technically a behavioral change, but does not affect the outcome. The reason for this is that the logic did retry, but the http client did immediately abort.
Introduce `retryOnAbort` retry option.
The client continue retries even if it was aborted by a timeout. This is achieved by re-initializing the AbortController. The idea behind this is to allow fast retries for slow request.
Associated to Issue https://github.com/commercetools/commercetools-sdk-typescript/issues/354
=> feat(http-client): add option to retry a request aborted by timeout

.changeset/fresh-melons-decide.md, packages/sdk-client/src/sdk-middleware-http/http.ts
Fix `uri not found error` when `includeRequestInErrorResponse` is set to false
#414
=> Fix Uri Not Found on 404 Error

.changeset/kind-taxis-flash.md, packages/sdk-client/src/sdk-middleware-http/http.ts
Fix issues with file uploads when using the SDK.
[#1837](https://github.com/commercetools/nodejs/pull/1837)
=> Fix 415 issues with image upload when using the SDK

.changeset/two-flies-lay.md, packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/test/http.test/http.test.ts
- Adds catch block to prevent unhandled promise rejection on parsing response text
=> Handle node-fetch text parse error in sdk client http middleware

README.md
Update broken `README.md` build badge.
=> Fix Broken README Build Badge

packages/history-sdk/tsconfig-declarations.json, packages/importapi-sdk/tsconfig-declarations.json, packages/ml-sdk/tsconfig-declarations.json, packages/platform-sdk/tsconfig-declarations.json
After update of `tsconfig-replace-paths` to version `0.0.14` generator builds started failing. This PR is an attempt to fix this.
=> Fix issues with tsconfig-declaration.json file

.github/workflows/create-pr.yml, .github/workflows/release.yml
Replaces the usage of a static long-lived PAT with a short-lived (auto revoked) PAT through a GitHub Application called CT Changesets.
This is being rolled out across about 10 repositories. More detail and background on the changes can be found on internal documentation.
=> Refactor to not use long-lived PAT but short-lived PAT issued by GitHub App

.changeset/curvy-fans-lick.md, jest.config.js, packages/sdk-client/src/sdk-middleware-http/http.ts, packages/sdk-client/src/types/sdk.d.ts, packages/sdk-client/test/http.test/http.test.ts
=> Add headersWithStringBody options

README.md
Removed `ml-sdk` from the packages table on the readme. This package is no longer available.
=> Remove ml-sdk from readme

.changeset/chatty-jobs-melt.md, package.json, packages/platform-sdk/test/integration-tests/client/client.test.ts, packages/platform-sdk/test/integration-tests/process/process.test.ts, packages/platform-sdk/test/integration-tests/test-utils.ts, packages/sdk-client/src/client-builder/ClientBuilder.ts, packages/sdk-client/src/types/sdk.d.ts, packages/sdk-client/test/client-builder.test/client-builder.test.ts
Add options that includer a `logger` function to be executed in place of the default
The PR fixes issue #653 
This implementation can be used as follows:
```ts
import {
...
type Next,
type Client,
type MiddlewareRequest,
type LoggerMiddlewareOptions,
type MiddlewareResponse,
} from '@commercetools/sdk-client-v2';
const client: Client = new ClientBuilder()
.withProjectKey(projectKey)
...
.withLoggerMiddleware({
level: 'debug',
name: 'custom-logger-fn',
logger(options?: LoggerMiddlewareOptions) {
return (next: Next): Next => {
return (req: MiddlewareRequest, res: MiddlewareResponse) => {
console.log(options);  // this will log all included option except the logger function i.e { level: 'debug', name: 'custom-logger-fn' }
console.log(req, res);
next(req, res);
}
}
}
}).build()
```
=> Add options for Custom Logger Function

package.json
Attempt to fix jest circle-ci repeated SIGKILL signal on node version 16
For some reason, node v16 is consuming excessive amount of memory. Rather than spend too much time debugging this issue, I think it will be wise to `temporarily` disable the parallelisation of the tests using `workers` this is because a plan is already underway to remove support for node v16.
Also, after the node version update, we will definitely go back to parallelising the tests once again.
=> Increase Jest Max Worker

.changeset/twelve-islands-change.md, packages/sdk-client-v3/src/client/client.ts
Fix error that results when retrying due to redacted OAuth token
[DevX-425](https://commercetools.atlassian.net/browse/DEVX-425)
=> [Fix] Error Due to Redacted OAuth Token

packages/platform-sdk/test/integration-tests/cart/cart.me.test.ts, packages/platform-sdk/test/integration-tests/cart/cart.test.ts, packages/platform-sdk/test/integration-tests/graphql/graphql.test.ts, packages/platform-sdk/test/integration-tests/message/message.test.ts, packages/platform-sdk/test/integration-tests/order/order.test.ts, packages/platform-sdk/test/integration-tests/product-projection/product-projection.test.ts, packages/platform-sdk/test/integration-tests/product-type/product-type-fixture.ts, packages/platform-sdk/test/integration-tests/product-type/product-type.test.ts, packages/platform-sdk/test/integration-tests/product/product.test.ts, packages/platform-sdk/test/integration-tests/sdk-v3/middlewares.test.ts
There was an issue that more than 1000 product types were created. This is the limit of CTP: https://docs.commercetools.com/api/limits#product-types. So, we need to ensure that the product type is created only if it does not exist. This PR checks if the product type exists before creating a new one.
=> fix(tests): check before create new product type

.changeset/hot-pans-exercise.md, packages/sdk-client-v3/src/middleware/auth-middleware/auth-request-executor.ts
Fix Typo error in `executor` function `Content-Length` headers entry.
=> [DEVX-434][FIX] Fix Typo Error in Executor Function

.changeset/purple-melons-share.md, examples/browser/browser.html, packages/sdk-client-v3/package.json, packages/sdk-client-v3/src/utils/byteLength.ts, packages/sdk-client-v3/tests/utils.test/byteLength.test.ts
Fix issues SDK unable to properly decode special character bytelengths
[ST-29177](https://commercetools.atlassian.net/browse/SUPPORT-29177)
=> [Fix][ST-29177] Issues with Special Characters ByteLength in SDK 

.changeset/grumpy-ways-drum.md, packages/platform-sdk/test/integration-tests/sdk-v3/error-cases.test.ts, packages/sdk-client-v3/README.md, packages/sdk-client-v3/src/middleware/create-http-middleware.ts, packages/sdk-client-v3/src/types/types.d.ts, packages/sdk-client-v3/src/utils/executor.ts
Fix issue with abortController always reusing the inital timedout controller
[#30038](https://commercetools.atlassian.net/browse/SUPPORT-30038?focusedCommentId=865938)
=> [Fix][DEVX-514] Fix v3 AbortController Retry Reinitialization

.changeset/breezy-sheep-count.md, packages/history-sdk/package.json, packages/importapi-sdk/package.json, packages/platform-sdk/package.json, packages/sdk-client-v3/package.json, packages/sdk-client/package.json, packages/ts-sdk-apm/package.json
I forgot to add the changeset for nodejs 16 support removal.
=> changeset: Remove. node 16 support

.changeset/afraid-squids-double.md, packages/platform-sdk/test/integration-tests/sdk-v3/response-serialization.test.ts, packages/sdk-client-v3/src/utils/executor.ts
Properly serialize raw response JSON object for `HEAD` requests
=> [Fix][DEVX-531] Issue with Response Serialization

.changeset/rare-feet-cheat.md, packages/sdk-client-v3/src/utils/userAgent.ts
Fix issue with missing `process` object in non supported environments like `React Native`
[1006](https://github.com/commercetools/commercetools-sdk-typescript/issues/1006)
=> [Fix] Issue with `process` Object in a non supported environments e.g React Native

.changeset/correlation-id-middleware.md, packages/sdk-client-v3/src/middleware/create-correlation-id-middleware.ts
Found out we had some errors: TypeError: Cannot read properties of undefined (reading 'generate').
Applied a fix. Maybe for future improvements, add some more and strict typescript config. That will prevent these kind of issues to be on production.
=> fix(middleware): use optional chaining for generate function

.changeset/sharp-files-end.md, packages/sdk-client-v3/src/middleware/create-http-middleware.ts, packages/sdk-client-v3/src/types/types.d.ts, packages/sdk-client-v3/src/utils/index.ts, packages/sdk-client-v3/src/utils/validate.ts, packages/sdk-client-v3/tests/http.test/http-middleware.test.ts
Sometimes we might want to stringify a request body before sending to server, this will allow the user to add custom header entries that force the request body to be stringified before sending it over to the backend.
This should now solve [this](https://github.com/commercetools/commercetools-sdk-typescript/issues/1039) open issue
=> [Feat][DEVX-619]: Add Custom `headersWithStringBody` to HttpMiddlewareOptions
