commercetools/commercetools-sdk-typescript

- generate-sdk.sh
- packages/ml-sdk/src/generated/client/attributes/by-project-key-missing-data-attributes-request-builder.ts
- packages/ml-sdk/src/generated/client/by-project-key-request-builder.ts
- packages/ml-sdk/src/generated/client/missing-data/by-project-key-missing-data-request-builder.ts
- packages/ml-sdk/src/generated/client/status/by-project-key-missing-data-attributes-status-by-task-id-request-builder.ts
- packages/ml-sdk/src/generated/client/status/by-project-key-missing-data-attributes-status-request-builder.ts
- packages/ml-sdk/src/generated/models/common.ts
- packages/ml-sdk/src/generated/models/missing-data.ts
- packages/ml-sdk/test/helpers/test-utils.ts
- packages/ml-sdk/test/missing-data.test.ts
Tip for review, skip the generated code and go straight for the tests 😄
> chore: add missing data

- packages/ml-sdk/src/generated/shared/utils/common-types.ts
- packages/platform-sdk/src/generated/models/cart-discount.ts
- packages/platform-sdk/src/generated/models/cart.ts
- packages/platform-sdk/src/generated/models/common.ts
- packages/platform-sdk/src/generated/models/error.ts
- packages/platform-sdk/src/generated/models/extension.ts
- packages/platform-sdk/src/generated/models/message.ts
- packages/platform-sdk/src/generated/models/order-edit.ts
- packages/platform-sdk/src/generated/models/order.ts
- packages/platform-sdk/src/generated/models/product-type.ts
- packages/platform-sdk/src/generated/models/project.ts
- packages/platform-sdk/src/generated/models/shipping-method.ts
- packages/platform-sdk/src/generated/models/subscription.ts
- packages/platform-sdk/src/generated/models/type.ts
- packages/platform-sdk/src/generated/shared/utils/common-types.ts
adding latest changes from raml spec
> chore: adding latest changes from raml spec

- packages/platform-sdk/src/generated/client/by-project-key-request-builder.ts
- packages/platform-sdk/src/generated/client/carts/by-project-key-carts-by-id-request-builder.ts
- packages/platform-sdk/src/generated/client/carts/by-project-key-carts-customer-id-by-customer-id-request-builder.ts
- packages/platform-sdk/src/generated/client/carts/by-project-key-in-store-key-by-store-key-carts-by-id-request-builder.ts
- packages/platform-sdk/src/generated/client/carts/by-project-key-in-store-key-by-store-key-carts-customer-id-by-customer-id-request-builder.ts
- packages/platform-sdk/src/generated/client/carts/by-project-key-in-store-key-by-store-key-carts-request-builder.ts
- packages/platform-sdk/src/generated/client/custom-objects/by-project-key-custom-objects-by-container-by-key-request-builder.ts
- packages/platform-sdk/src/generated/client/custom-objects/by-project-key-custom-objects-by-id-request-builder.ts
- packages/platform-sdk/src/generated/client/customers/by-project-key-in-store-key-by-store-key-customers-by-id-request-builder.ts
- packages/platform-sdk/src/generated/client/customers/by-project-key-in-store-key-by-store-key-customers-key-by-key-request-builder.ts
- packages/platform-sdk/src/generated/client/customers/by-project-key-in-store-key-by-store-key-customers-request-builder.ts
- packages/platform-sdk/src/generated/client/orders/by-project-key-in-store-key-by-store-key-orders-by-id-request-builder.ts
- packages/platform-sdk/src/generated/client/orders/by-project-key-in-store-key-by-store-key-orders-order-number-by-order-number-request-builder.ts
- packages/platform-sdk/src/generated/client/orders/by-project-key-in-store-key-by-store-key-orders-request-builder.ts
- packages/platform-sdk/src/generated/client/orders/by-project-key-me-orders-by-id-request-builder.ts
- packages/platform-sdk/src/generated/models/cart-discount.ts
- packages/platform-sdk/src/generated/models/cart.ts
- packages/platform-sdk/src/generated/models/common.ts
- packages/platform-sdk/src/generated/models/error.ts
- packages/platform-sdk/src/generated/models/extension.ts
- packages/platform-sdk/src/generated/models/message.ts
- packages/platform-sdk/src/generated/models/order-edit.ts
- packages/platform-sdk/src/generated/models/order.ts
- packages/platform-sdk/src/generated/models/product-type.ts
- packages/platform-sdk/src/generated/models/project.ts
- packages/platform-sdk/src/generated/models/shipping-method.ts
- packages/platform-sdk/src/generated/models/store.ts
- packages/platform-sdk/src/generated/models/subscription.ts
- packages/platform-sdk/src/generated/models/type.ts
> improvement: add latest changes

- packages/ml-sdk/package.json
fix module dependency test issue
> fix module dependency test issue

- .gitignore
- packages/sdk-client/package.json
- packages/sdk-client/src/builder/ClientBuilder.ts
- packages/sdk-client/src/http-user-agent/create-user-agent.ts
- packages/sdk-client/src/index.ts
- packages/sdk-client/src/sdk-middleware-user-agent/user-agent.ts
- packages/sdk-client/src/types/sdk.d.ts
- packages/sdk-client/test/create-user-agent.test/user-agent.test.ts
- packages/sdk-client/test/user-agent.test/user-agent.test.ts
Fix user agent to conform with the new accepted format.
> Fix User Agent to Conform With the New Format

- .circleci/config.yml
- README.md
- jest.config.js
- package.json
- yarn.lock
> Small Repository Improvements

- README.md
- packages/history-sdk/README.md
- packages/importapi-sdk/README.md
- packages/ml-sdk/README.md
- packages/platform-sdk/README.md
- packages/sdk-client/README.md
- Update all package README.md file to use sdk-client-v2
- Include usage examples and documentations
- Remove links related to old (nodejs) sdk-client
> Update all Package README.md 

- .changeset/strange-timers-travel.md
- packages/platform-sdk/package.json
> Update Dependency Tree

- .changeset/long-hornets-grab.md
- packages/sdk-client/package.json
Add buffer as a dependency to `sdk-client` package
> Add Buffer Dependency

- examples/me/README.md
- examples/me/client/src/component/Cart.jsx
- examples/me/client/src/component/Details.jsx
- examples/me/client/src/component/Merge.jsx
- examples/me/client/src/component/Modal.jsx
- examples/me/client/src/component/Nav.jsx
- examples/me/client/src/component/Product.jsx
- examples/me/client/src/constants/index.js
- examples/me/client/store/cart/cartAction.js
- examples/me/client/store/cart/cartReducer.js
- examples/me/server/src/repository/CartRepository.ts
> Refactor Currency Code

- packages/sdk-client/src/sdk-middleware-http/http.ts
- packages/sdk-client/test/http.test/http.test.ts
- Add check for explicitly set "Content-Type" headers
- Add tests to to validate functionality
> Add feature for multipart/form-data (File) Uploads

- README.md
- packages/sdk-client/src/index.ts
- packages/sdk-client/src/sdk-client/client.ts
- packages/sdk-client/src/sdk-client/index.ts
- packages/sdk-client/test/client.test/sdk-client.test.ts
- refactor the client to expose the process function at the client level
- write tests to ensure new and existing features still works properly
#217
> Expose Client Process Function

- package.json
- packages/sdk-client/src/client-builder/ClientBuilder.ts
- packages/sdk-client/src/http-user-agent/create-user-agent.ts
- packages/sdk-client/src/sdk-middleware-user-agent/user-agent.ts
- packages/sdk-client/src/types/sdk.d.ts
- packages/sdk-client/test/user-agent.test/user-agent.test.ts
- add option to HttpUserAgentOptions to extend existing user agent
- add test to validate functionality
#223
> Add Option to Extend User-Agent

- packages/sdk-client/src/client-builder/ClientBuilder.ts
- packages/sdk-client/src/sdk-middleware-user-agent/user-agent.ts
- packages/sdk-client/src/types/sdk.d.ts
- Add middleware option to extend UserAgent.
- Remove the existing types on node-fetch function
> Make User Agent Option Optional

- .changeset/smart-bananas-pretend.md
Pull request to release latest changes on base branch.
> Release New Typescript SDK

- examples/me/README.md
I have re-written this readme based on my experience setting up this application.
> Rewrite of ME Endpoint Checkout App readme file

- .changeset/giant-kiwis-rhyme.md
> Release Latest TypeScript SDK

- BEST_PRACTICES.md
- README.md
> Add Best Practices Markdown File to Repository

- package.json
> Debug Webpack Build Issues

- .changeset/beige-ghosts-agree.md
- examples/me/server/yarn.lock
- packages/sdk-client/src/client-builder/ClientBuilder.ts
- packages/sdk-client/src/sdk-middleware-concurrent-modification/concurrent-modification.ts
- packages/sdk-client/src/sdk-middleware-concurrent-modification/index.ts
- packages/sdk-client/src/types/sdk.d.ts
- packages/sdk-client/test/client-builder.test/client-builder.test.ts
- packages/sdk-client/test/concurrent-modification.test/concurrent-modification.test.ts
> Implement Concurrent Modification (409) Error Handler

- .changeset/ninety-pots-change.md
- packages/sdk-client/src/sdk-middleware-auth/base-auth-flow.ts
> Reduce Token Fetch Window

- .changeset/early-pets-battle.md
> Add changeset and detailed descriptions generated changes

- .changeset/shaggy-keys-repair.md
- packages/sdk-client/src/sdk-middleware-auth/anonymous-session-flow.ts
- packages/sdk-client/src/sdk-middleware-auth/password-flow.ts
- packages/sdk-client/src/sdk-middleware-auth/refresh-token-flow.ts
- packages/sdk-client/src/types/sdk.d.ts
- packages/sdk-client/test/auth.test/anonymous-session-flow.test.ts
> Fix TokenCache Store

- .changeset/olive-panthers-smell.md
- packages/sdk-client/src/sdk-middleware-auth/anonymous-session-flow.ts
- packages/sdk-client/src/sdk-middleware-auth/client-credentials-flow.ts
- packages/sdk-client/src/sdk-middleware-auth/password-flow.ts
- packages/sdk-client/src/sdk-middleware-auth/refresh-token-flow.ts
- packages/sdk-client/src/sdk-middleware-auth/utils.ts
- packages/sdk-client/src/types/sdk.d.ts
- packages/sdk-client/test/auth.test/base-auth-flow.test.ts
> Fix (store): add proper generic type for store function

- .changeset/good-zoos-obey.md
- .changeset/serious-mangos-exercise.md
> chore(changeset): add SDK changes to changeset

- .circleci/config.yml
- examples/package.json
- examples/test/browser.test.js
- examples/yarn.lock
> Fix failing tests

- .changeset/slow-dolls-shout.md
- packages/history-sdk/src/generated/shared/utils/uri-utils.ts
- packages/history-sdk/test/utils/uri-utils.test.ts
- packages/importapi-sdk/src/generated/shared/utils/uri-utils.ts
- packages/importapi-sdk/test/utils/uri-utils.test.ts
- packages/ml-sdk/src/generated/shared/utils/uri-utils.ts
- packages/ml-sdk/test/utils/uri-utils.test.ts
- packages/platform-sdk/src/generated/shared/utils/uri-utils.ts
- packages/sdk-client-v3/package.json
- packages/sdk-client-v3/src/client/client.ts
- packages/sdk-client-v3/src/utils/index.ts
- packages/sdk-client-v3/tests/client.test/client.test.ts
- packages/sdk-client-v3/tests/utils.test/url.test.ts
- packages/sdk-client/test/utils.test/url.test.ts
- yarn.lock
Remove remaining `querystring` packages
None
> chore(querystring): remove all querystring

- .circleci/config.yml
- README.md
- jest.config.js
- package.json
- packages/platform-sdk/test/integration-tests/cart-discount/cart-discount-fixture.ts
- packages/platform-sdk/test/integration-tests/cart-discount/cart-discount.test.ts
- packages/platform-sdk/test/integration-tests/cart/cart.test.ts
- packages/platform-sdk/test/integration-tests/custom-object/custom-object.test.ts
- packages/platform-sdk/test/integration-tests/order/order-fixture.ts
- packages/platform-sdk/test/integration-tests/order/order.test.ts
- packages/platform-sdk/test/integration-tests/product-discount/product-discount-fixture.ts
- packages/platform-sdk/test/integration-tests/product-discount/product-discount.test.ts
- packages/platform-sdk/test/integration-tests/product-projection/product-projection.test.ts
- packages/platform-sdk/test/integration-tests/product/product-fixture.ts
- packages/platform-sdk/test/integration-tests/test-utils.ts
- yarn.lock
- Category
- Cart
- Cart Discount
- Channel
- Custom Object
- Customer
- Customer => customerClone is testing mixin file -> not applicable here
- Customer Group
- Discount Code
- Extension
- GraphQL
- Inventory
- Message
- Payment
- Product
- Product Discount
- Product Projection
- Product Type
- Project
- Review
- Shipping Method
- Shopping List
- State
- Store
- Subscription
- Tax Category
- Type
- Zone
> Devx 52 integration tests examples

- examples/newrelic-express-apm/.env.sample
- examples/newrelic-express-apm/package.json
- examples/newrelic-express-apm/requests.txt
- examples/newrelic-express-apm/src/controller/CartController.js
- examples/newrelic-express-apm/src/controller/CartDiscountController.js
- examples/newrelic-express-apm/src/controller/index.js
- examples/newrelic-express-apm/src/routes/cart-discount.js
- examples/newrelic-express-apm/src/routes/cart.js
- examples/newrelic-express-apm/src/routes/index.js
- examples/newrelic-express-apm/src/sdk-v2/sdk.js
- examples/newrelic-express-apm/src/service/CartDiscountService.js
- examples/newrelic-express-apm/src/service/CartService.js
- examples/newrelic-express-apm/src/service/index.js
- examples/newrelic-express-apm/yarn.lock
> Update repository examples

- packages/sdk-client-v3/package.json
- packages/sdk-client-v3/src/utils/generateID.ts
- yarn.lock
Fix issues with failing preconstruct builds.
> Fix issues with failing builds

- packages/history-sdk/package.json
- packages/importapi-sdk/package.json
- packages/ml-sdk/package.json
- packages/platform-sdk/package.json
> Fix issues with tsconfig-declarations-json

- .changeset/big-birds-hide.md
- packages/ts-sdk-apm/src/apm.ts
Add a useragent header to the `ts-sdk-apm` headers
> Add UserAgent Header Key

- .changeset/loud-bats-relate.md
- packages/sdk-client/src/client-builder/ClientBuilder.ts
> Remove APM user agent version

- .github/workflows/docs.yml
- .gitignore
- README.md
- package.json
- typedoc.cjs
- yarn.lock
Implement sdk type docs specifications
> Implement SDK TypeDocs Specifications

- examples/newrelic-express-apm/package.json
- examples/react-webpack/package.json
- examples/react-webpack/yarn.lock
Fix remaining security vulnerabilities
> [Chore] Fix Security Vulnerability

- examples/me/client/webpack.config.js
> Specify a directory for the static files in development mode

- .github/workflows/docs.yml
- tsconfig.json
Fix issues with typescript code generator
> Comment off references from tsconfig.json file

- packages/platform-sdk/test/__setup__/setup.js
- packages/platform-sdk/test/integration-tests/sdk-v3/middlewares.test.ts
- packages/platform-sdk/test/integration-tests/test-utils.ts
- packages/sdk-client-v3/src/types/types.d.ts
- yarn.lock
Fix failing tests due to incorrect typescript type definitions
Fixes failing tests in https://github.com/commercetools/commercetools-sdk-typescript/pull/716
> Fix Issues with Typescript Types Definitions

- .changeset/metal-readers-leave.md
- packages/sdk-client-v3/src/middleware/auth-middleware/auth-request-executor.ts
Reset the token fetch signal state to default on error
> [Fix] Reset The Token Request State on Error

- .github/workflows/release.yml
Update Github workflow `release.yml` file.
> [Chore] Update `release.yml` github workflow file

- .changeset/tidy-bears-swim.md
- packages/sdk-client-v3/src/client/client.ts
- packages/sdk-client-v3/src/middleware/auth-middleware/anonymous-session-flow.ts
- packages/sdk-client-v3/src/middleware/auth-middleware/password-flow.ts
- packages/sdk-client-v3/src/middleware/auth-middleware/refresh-token-flow.ts
- packages/sdk-client-v3/src/types/types.d.ts
- packages/sdk-client-v3/tests/auth/anonymous-flow.test.ts
- packages/sdk-client-v3/tests/auth/refresh-token.test.ts
Fix concurrency in TypeScript V3 SDK.
#761
> [Fix][DEVX-461] Concurrency issue in TypeScript SDK

- .changeset/smooth-pianos-invent.md
- packages/sdk-client-v3/src/utils/executor.ts
Remove the `Accept -Encoding` header entry
https://commercetools.atlassian.net/browse/DEVX-532
> [Fix][DEVX-532] Remove Accept-Encoding Header Entry

- .changeset/soft-geese-sniff.md
- packages/importapi-sdk/test/integration/import.test.ts
- packages/platform-sdk/test/integration-tests/sdk-v3/image.test.ts
- packages/sdk-client-v3/src/utils/byteLength.ts
- packages/sdk-client-v3/tests/utils.test/byteLength.test.ts
Fix issues with character encoding
> [Fix] Issues with Non-ASCII Character Encoding

- .changeset/strong-windows-breathe.md
Release the Typescript APM package
> [Chore] Release Latest Typescript SDK APM package

- examples/datadog-express-apm/container-agent/package.json
- examples/datadog-express-apm/host-agent/package.json
Rename packages with the same (colliding) names
> [Chore] Rename Colliding Package Names

- .github/workflows/release.yml
Fix authorization header in workflow file
> [Chore] Fix Authorization Header in Workflow File

- examples/vue-example-app/.vscode/extensions.json
- examples/vue-example-app/.vscode/settings.json
- jest.config.js
- packages/history-sdk/package.json
- packages/history-sdk/test/helpers/api-helpers.ts
- packages/history-sdk/test/helpers/test-utils.ts
- packages/history-sdk/test/misc.test.ts
- packages/importapi-sdk/package.json
- packages/importapi-sdk/test/helpers/ctp-api-helper.ts
- packages/importapi-sdk/test/helpers/test-utils.ts
- packages/importapi-sdk/test/misc.test.ts
- packages/platform-sdk/package.json
- packages/platform-sdk/test/helpers/ctp-api-helper.ts
- packages/platform-sdk/test/helpers/test-utils.ts
- packages/platform-sdk/test/integration-tests/order/order-fixture.ts
- packages/platform-sdk/test/integration-tests/order/order.test.ts
- packages/platform-sdk/test/integration-tests/test-utils.ts
- packages/sdk-client-v3/tests/http.test/http-middleware.test.ts
- packages/ts-sdk-apm/src/apm.ts
- packages/ts-sdk-apm/test/apm.test/apm.test.ts
- yarn.lock
Remove old client (sdk-client-v2) from running tests suites
> [Chore][DEVX-572] Remove Old Client from Test

- package.json
- packages/ts-sdk-apm/package.json
- yarn.lock
> [Chore] Fix CVE security alerts

- examples/react-vite/package.json
Update transitive `vite` dependency to fix vulnerable `esbuild` dependency.
> [Chore] Update Vite

- .changeset/brave-yaks-join.md
- packages/platform-sdk/test/integration-tests/order/order.test.ts
- packages/ts-sdk-apm/src/apm.ts
- packages/ts-sdk-apm/test/apm.test/apm.test.ts
Fix issue with telemetry `apm` and `tracer` function not being called
> [Fix] Issue With Telemetry Package

- .changeset/vast-moles-argue.md
- packages/sdk-client-v3/src/utils/userAgent.ts
Fix typographical error in the client user agent
> [Fix] Typographical Error

- packages/platform-sdk/test/integration-tests/standalone-prices/standalone-prices-fixtures.ts
- packages/platform-sdk/test/integration-tests/standalone-prices/standalone-prices.test.ts
- packages/platform-sdk/test/integration-tests/test-utils.ts
Attempt to fix Standalone Price by rewriting it
> [Chore] Rewrite Standalone Prices Tests

- .changeset/nice-dryers-relate.md
- packages/sdk-client-v3/src/client/client.ts
- packages/sdk-client-v3/src/types/types.d.ts
- packages/sdk-client-v3/tests/client.test/client.test.ts
- tsconfig.json
Improve typescript type definitions
> [Chore] Improve Typescript SDK Type Definitions

- .changeset/gentle-clubs-hang.md
> [Chore] Add Release Changeset
